from . import subcategory
from . import service
from . import service_request
from . import equipment
from . import equipment_category
from . import maintenance_request
from . import maintenance_requisition
from . import spare_details
from . import preventive_maintenance_check
from . import machine_history
from . import corrective_maintenance
from . import company_properties