{
    'name': 'Delivery Challan',
    'version': '17.0.0.56',
    'category': 'Warehouses',
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
    'description': """ Delivery Challan""",
    'summary': 'Delivery Challan',
    'author': 'AppsComp Widgets Pvt Ltd',
    'website': 'www.appscomp.com',
    'depends': ['stock', 'material_request', 'quality_extension'],
    'data': [
        'security/ir.model.access.csv',
        'data/stock_operation_type.xml',
        'views/stock_picking.xml',
        'views/res_config_view.xml',
        'views/job_work_type.xml',
        'reports/dc_report.xml',
        # 'reports/job_order_report.xml',
        'reports/job_order_cum_dc_new.xml',
    ],
    'installable': True,
    'currency': 'EUR',
    'active': True,
}
