{
    'name': 'HR Payroll Extended',
    'version': '17.109',
    'summary': '',
    'description': """ HR Payroll Extended """,
    'category': 'Human Resources/Employees',
    'author': 'AppsComp Widgets Pvt Ltd',
    'website': 'https://www.appscomp.com',
    'depends': ['hr', 'hr_payroll', 'base', 'hr_work_entry_contract_enterprise', 'hr_attendance', 'hr_holidays',
                'hr_payroll_holidays', 'mail', 'web_editor','hr_holidays_balance_report' ],
    'data': [
        'data/staff_pay_and_sat.xml',
        'data/groups.xml',
        'data/base_data.xml',
        'data/time_off_data.xml',
        'data/excel_payslip_template_data.xml',
        'data/hr_payroll_structure_data.xml',
        'data/hr_payroll_staff_structure_data.xml',
        'data/ir_sequence.xml',
        'data/hr_salary_rule_category_data.xml',
        'views/hr_payroll_year.xml',
        'security/ir.model.access.csv',
        'views/hr_employee.xml',
        'views/hr_contract_views.xml',
        'views/hr_public_holidays_view.xml',
        'views/hr_payslip_views.xml',
        'views/esi_report_views.xml',
        'views/skill_matrix.xml',
        'views/pf_report.xml',
        'views/payslip_excel_import.xml',
        'views/payslip_excel_template.xml',
        'views/payrol_res_config_view.xml',
        'views/hr_leave_view.xml',
        'views/time_off.xml',
        'views/hr_attendance.xml',
        'views/shift_master.xml',
        'wizard/attendance_report_view.xml',
        'report/hr_advance_report.xml',
        'report/employee_contract_report.xml',
        'report/attendance_report_pdf_view.xml',
        'report/public_holiday_report.xml',
        'report/payslip_report_pdf_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # 'hr_payroll_extended/static/css/custom_style.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
