{
    'name': 'Manufacturing Process',
    'version': '17.10',
    'summary': '',
    'description': """ For Managing Manufacturing Process """,
    'category': 'Manufacturing',
    'author': 'AppsComp Widgets Pvt Ltd',
    'website': 'https://www.appscomp.com',
    'depends': ['base', 'stock', 'inventory_extended', 'mrp_plm', 'mail', 'mrp', 'purchase', 'delivery_challan', 'quality_extension', 'merge_delivery_dc', 'account', 'quality_control'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/ir_sequence.xml',
        'views/part_operation_view.xml',
        'views/process_routing.xml',
        'views/std_container_view.xml',
        'views/customer_release.xml',
        'views/mrp_dashboard_views.xml',
        'views/operation_view.xml',
        'views/job_planningview.xml',
        'views/customer_release_dashboard.xml',
        'views/production_dashboard_view.xml',
        'views/production_session.xml',
        'views/product_template.xml',
        'views/mrp_productivity_view.xml',
        'views/job_order_tracking.xml',
        'views/mrp_production_view.xml',
        'views/productivity_tracking.xml',
        'views/quality_inherit_view.xml',
        'views/reject_rework_lot.xml',
        'views/stock_lot.xml',
        'wizard/process_routing_wizard.xml',
        'wizard/reject_handing.xml',
        'reports/process_routing_report.xml',
        'reports/finished_job_report.xml',
        'reports/single_productivity_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'manufacturing_extended/static/src/js/process_routing_report.js',
            'manufacturing_extended/static/src/js/mrp_dashboard.js',
            'manufacturing_extended/static/src/js/customer_release.js',
            'manufacturing_extended/static/src/js/production_dashboard.js',
            'manufacturing_extended/static/src/js/productivity_dashboard.js',
            'manufacturing_extended/static/src/xml/process_routing_report.xml',
            'manufacturing_extended/static/src/xml/mrp_dashboard_view.xml',
            'manufacturing_extended/static/src/xml/cr_dashboard.xml',
            'manufacturing_extended/static/src/xml/production_dashboard.xml',
            'manufacturing_extended/static/src/xml/productivity_dashboard.xml',
            'web/static/lib/select2/select2.css',
            'web/static/lib/select2/select2.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
