{
    'name': 'Supplier Performance',
    'version': '17.20',
    'summary': '',
    'description': """ Supplier Performance Excel Report""",
    'category': 'Stock',
    'author': 'AppsComp Widgets Pvt Ltd',
    'website': 'https://www.appscomp.com',
    'depends': ['purchase', 'stock', 'hr_payroll_extended', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir.sequence.xml',
        'report/grn_label_report.xml',
        'views/supplier_perfomance.xml',
        'views/supplier_perfom_views.xml',
        'views/score_card.xml',
        'views/purchase_order_excel.xml',
        'views/service_po_excel_views.xml',
        'views/pending_service_po_report_views.xml',
        'views/pending_po_excel_views.xml',
        'views/stock_move_views.xml',
        'views/rfq_report_excel_views.xml',
        'views/pending_grn_report.xml',
        'views/grn_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
