from . import hr_payroll_year
from . import hr_employee
from . import hr_payslip
from . import hr_contract
from . import hr_public_holidays
from . import payslip_excel_import
from . import payslip_excel_template
from . import payslip_excel_template
from . import skill_matrix
from . import half_round
from . import time_off
from . import shift_master